# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('type', models.IntegerField(default=0)),
                ('insertDate', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
